//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by mapedit.rc
//
#define IDR_MAINMENU                    101
#define MAINICON                        102
#define FILEICON                        103
#define IDD_ABOUTBOX                    104
#define IDC_CURSOR_SELECT               106
#define IDC_CURSOR_SELDRAG              107
#define IDC_CURSOR_DRAG                 108
#define IDC_CURSOR_COPY                 110
#define IDC_ICONDISP                    1000
#define IDC_PRODUCTNAME                 1001
#define IDC_DEVELOPER                   1002
#define IDC_LICENCE                     1003
#define IDC_GITHUBLINK                  1006
#define ID_FILE_NEW_FROMSCRATCH         40001
#define ID_FILE_NEW_FROMPCXFILE         40002
#define ID_FILE_SAVEAS                  40005
#define ID_FILE_EXIT                    40008
#define ID_FILE_OPENRECENT_EMPTY        40009
#define ID_EDIT_CHANGEFIELDTYPE_ORDINARYFIELD 40011
#define ID_EDIT_CHANGEFIELDTYPE_SOLUTIONFIELD_CONTINUING 40012
#define ID_EDIT_CHANGEFIELDTYPE_SOLUTIONFIELD_FIRSTLEFT 40013
#define ID_EDIT_CHANGEFIELDTYPE_SOLUTIONFIELD_FIRSTTOP 40014
#define ID_EDIT_CHANGEFIELDTYPE_HELPFIELD_SINGLE 40015
#define ID_EDIT_CHANGEFIELDTYPE_HELPFIELD_DOUBLE 40016
#define ID_EDIT_CHANGEFIELDTYPE_DECORATIONFIELD_VARIANTA 40017
#define ID_EDIT_CHANGEFIELDTYPE_DECORATIONFIELD_VARIANTB 40018
#define ID_EDIT_CHANGEFIELDTYPE_AIDSFIELD 40019
#define ID_EDIT_CHANGEFIELDTYPE_ILLUSTRATIONOCCUPIEDFIELD 40020
#define ID_EDIT_EDITSOLUTIONFORMAT      40021
#define ID_EDIT_EDITCAPTION             40022
#define ID_EDIT_CHANGELANGUAGE_CZECH    40026
#define ID_EDIT_CHANGELANGUAGE_ENGLISH  40027
#define ID_VIEW_SHOWPCXMAP              40028
#define ID_VIEW_SHOWSOLUTION            40029
#define ID_HELP_CONTENTS                40030
#define ID_HELP_ABOUT                   40031
#define ID_TOOLS_CONVERTEROFPCXINDEXMAP 40032
#define ID_TOOLS_GITHUBISSUETRACKER     40033

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        116
#define _APS_NEXT_COMMAND_VALUE         40034
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
